### ISSUE TITLE
Do not use color on e.g. dumb and vt100 terminals

### ISSUE THREAD

**Issue by bbarker** [rust-pretty-assertions/rust-pretty-assertions#125]
I realize that obviates the purpose of this crate, but running code using this in settings where we have terminals without color support is a possibility. I briefly looked into modifying the macros to call std::assert_eq in such a case, but there's at least one reason why that seems a bad idea - we have the option of using no_std in this crate.

**Comment by tommilligan** [comment]
Duplicates #31 - there is desire for the same functionality there, if you'd like to join/collaborate on that discussion.
